In [ ]:
import pandas as pd
import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re

In [4]:
data=pd.read_csv('spotify_millsongdata.csv')
data

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \nAnd..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \nTouch me gentl..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \nWhy I had t...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...
...,...,...,...,...
57645,Ziggy Marley,Good Old Days,/z/ziggy+marley/good+old+days_10198588.html,Irie days come on play \nLet the angels fly l...
57646,Ziggy Marley,Hand To Mouth,/z/ziggy+marley/hand+to+mouth_20531167.html,Power to the workers \nMore power \nPower to...
57647,Zwan,Come With Me,/z/zwan/come+with+me_20148981.html,all you need \nis something i'll believe \nf...
57648,Zwan,Desire,/z/zwan/desire_20148986.html,northern star \nam i frightened \nwhere can ...
57649,Zwan,Heartsong,/z/zwan/heartsong_20148991.html,come in \nmake yourself at home \ni'm a bit ...

In [5]:
data.groupby(['artist']).count().sort_values(by='song',ascending=True)

                  song  link  text
artist
U-Kiss               1     1     1
X-Treme              1     1     1
Zoe                  1     1     1
Zed                  1     1     1
Ungu                 2     2     2
...                ...   ...   ...
Cher               187   187   187
George Strait      188   188   188
Bob Dylan          188   188   188
Gordon Lightfoot   189   189   189
Donna Summer       191   191   191

[643 rows x 3 columns]

In [ ]:
artist_counts = data['artist'].value_counts()
top_artists = artist_counts[artist_counts >= 180].index
df_main = data[data['artist'].isin(top_artists)]

df_tail = data[~data['artist'].isin(top_artists)].sample(frac=0.1, random_state=42)

data = pd.concat([df_main, df_tail])
data.shape

(4607, 4)

In [8]:
data.groupby(['artist']).count().sort_values(by='song',ascending=True)

                  song  link  text
artist
Beautiful South      1     1     1
Yo La Tengo          1     1     1
Bette Midler         1     1     1
Bill Withers         1     1     1
Billie Holiday       1     1     1
...                ...   ...   ...
Cher               187   187   187
George Strait      188   188   188
Bob Dylan          188   188   188
Gordon Lightfoot   189   189   189
Donna Summer       191   191   191

[342 rows x 3 columns]

In [ ]:
import nltk
nltk.download('punkt')
nltk.data.find('tokenizers/punkt')
nltk.download('stopwords')
nltk.data.find('corpora/stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\osama\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\osama\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\osama\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
from nltk.stem import WordNetLemmatizer

stop_words = set(stopwords.words('english'))
nltk.download('wordnet', download_dir='C:/nltk_data')
nltk.download('omw-1.4', download_dir='C:/nltk_data')

lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    text = re.sub(r"[^a-zA-Z\s]", "", str(text))
    text = text.lower()
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word not in stop_words]
    tokens = [lemmatizer.lemmatize(word) for word in tokens] 
    return " ".join(tokens)

[nltk_data] Downloading package punkt to C:/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to C:/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [ ]:
artist_counts = data["artist"].value_counts()

over_100 = artist_counts[artist_counts > 50].index

filtered_parts = []
for artist in over_100:
    artist_data = data[data["artist"] == artist]
    filtered_parts.append(artist_data.sample(frac=0.1, random_state=42))

under_100 = data[~data["artist"].isin(over_100)]

data = pd.concat([under_100, *filtered_parts]).reset_index(drop=True)
data

,artist,song,link,text
0,Ed Sheeran,Paralyzed,/e/ed+sheeran/paralyzed_20989927.html,If should glass kill \nThe arms in could and ...
1,Jason Mraz,It's Gonna Be A Good Day,/j/jason+mraz/its+gonna+be+a+good+day_21062531...,Verse \nFall out of bed and catch a fading st...
2,Jim Croce,This Land Is Your Land,/j/jim+croce/this+land+is+your+land_20493781.html,This land is your land \nThis land is my land...
3,Overkill,The Sound Of Dying,/o/overkill/the+sound+of+dying_20271313.html,Listen up now \nGot a fistful of reason \nAn...
4,HIM,Resurrection,/h/him/resurrection_10139980.html,There was a time \nWhen I could breath my lif...
...,...,...,...,...
2561,Fleetwood Mac,Heart Of Stone,/f/fleetwood+mac/heart+of+stone_20054482.html,Oh I have seen \nSuch madness in the air \nJ...
2562,Fleetwood Mac,Dust,/f/fleetwood+mac/dust_20054150.html,When the white flame in us is gone \nAnd we t...
2563,Fleetwood Mac,No Place To Go,/f/fleetwood+mac/no+place+to+go_20054347.html,"How many more year, have you got to wreck my l..."
2564,Fleetwood Mac,Child Of Mine,/f/fleetwood+mac/child+of+mine_20054148.html,Little child of mine \nYou'll be lovin' like ...
2565,Fleetwood Mac,Don't Stop,/f/fleetwood+mac/dont+stop_20054276.html,If you wake up and don't want to smile \nIf i...

In [13]:
data['cleaned_text'] = data['text'].apply(preprocess_text)

In [ ]:
import re
import yt_dlp
import pandas as pd
from concurrent.futures import ThreadPoolExecutor, as_completed


def extract_info_from_link(link: str):
    try:
        parts = link.strip("/").split("/")
        if len(parts) < 3:
            return None, None
        artist_slug = parts[1].replace("+", " ").title()
        song_slug   = parts[2].rsplit("_", 1)[0]
        song_name   = song_slug.replace("+", " ").title()
        return artist_slug, song_name
    except Exception:
        return None, None


def title_matches(title: str, song: str) -> bool:
    title_clean = re.sub(r'[^a-z0-9 ]', ' ', title.lower()).strip()
    song_clean  = re.sub(r'[^a-z0-9 ]', ' ', song.lower()).strip()
    return bool(re.search(rf'\b{re.escape(song_clean)}\b', title_clean))


def channel_matches(channel: str, artist: str) -> bool:
    channel_clean = re.sub(r'[^a-z0-9 ]', ' ', channel.lower()).strip()
    artist_clean  = re.sub(r'[^a-z0-9 ]', ' ', artist.lower()).strip()
    return bool(re.match(rf'^{re.escape(artist_clean)}(\s|$)', channel_clean))


def get_youtube_info(idx: int, artist: str, song: str, total: int) -> dict:
    empty = {"idx": idx, "youtube_link": None, "views": None, "likes": None}

    if not artist or not song:
        return empty

    ydl_opts_search = {"quiet": True, "no_warnings": True, "extract_flat": True}
    ydl_opts_detail = {"quiet": True, "no_warnings": True}

    try:
        with yt_dlp.YoutubeDL(ydl_opts_search) as ydl:
            results  = ydl.extract_info(f"ytsearch10:{artist} {song}", download=False)
            entries  = results.get("entries", [])
            matched  = [e for e in entries if title_matches(e.get("title", ""), song)]
            candidates = matched if matched else entries
            from_artist = [e for e in candidates if channel_matches(e.get("channel", ""), artist)]
            best = (
                max(from_artist, key=lambda e: e.get("view_count") or 0)
                if from_artist else
                max(candidates,  key=lambda e: e.get("view_count") or 0)
            )
            video_id = best["id"]

    except Exception as e:
        print(f"  [{idx}/{total}] ⚠️ Search error: {e}")
        return empty

    try:
        with yt_dlp.YoutubeDL(ydl_opts_detail) as ydl:
            info = ydl.extract_info(f"https://youtube.com/watch?v={video_id}", download=False)
            print(f"  [{idx}/{total}] ✅ {artist} — {song}")
            return {
                "idx":          idx,
                "youtube_link": f"https://youtube.com/watch?v={video_id}",
                "views":        info.get("view_count"),
                "likes":        info.get("like_count"),
            }

    except Exception as e:
        print(f"  [{idx}/{total}] ⚠️ Detail error: {e}")
        return {
            "idx":          idx,
            "youtube_link": f"https://youtube.com/watch?v={video_id}",
            "views":        best.get("view_count"),
            "likes":        None,
        }


total = len(data)

tasks = []
for i, (_, row) in enumerate(data.iterrows(), 1):
    artist, song = extract_info_from_link(row["link"])
    tasks.append((i, artist, song))

results = [None] * total

with ThreadPoolExecutor(max_workers=10) as executor:
    futures = {
        executor.submit(get_youtube_info, i, artist, song, total): i
        for i, artist, song in tasks
    }
    for future in as_completed(futures):
        result = future.result()
        results[result["idx"] - 1] = result

data["youtube_link"] = [r["youtube_link"] for r in results]
data["views"]        = [r["views"]        for r in results]
data["likes"]        = [r["likes"]        for r in results]

data.to_csv("cleaned_spotify_millsongdata.csv", index=False)

# Cleaned Dataset

In [20]:
df = pd.read_csv("cleaned_spotify_millsongdata.csv")

df.head()

,artist,song,link,text,cleaned_text,youtube_link,views,likes
0,Bonnie Raitt,I Believe I'm In Love With You.,/b/bonnie+raitt/i+believe+im+in+love+with+you_...,I don't know what's wrong with me \nI've been...,dont know whats wrong ive foolish fool baby ca...,https://youtube.com/watch?v=Si0teRtHY8o,804405.0,12338.0
1,Patsy Cline,Have You Ever Been Lonely,/p/patsy+cline/have+you+ever+been+lonely_10200...,Have you ever been lonely have you ever been b...,ever lonely ever blue ever loved someone love ...,https://youtube.com/watch?v=PYq9CZwjis4,527978.0,5407.0
2,Ofra Haza,Kol Haklafim,/o/ofra+haza/kol+haklafim_10196740.html,Hakol beyneynu nigmar \nHatza'er li lo 'azar ...,hakol beyneynu nigmar hatzaer li lo azar hazma...,https://youtube.com/watch?v=UAjS5WMzmr8,517.0,11.0
3,Peter Cetera,One Clear Voice,/p/peter+cetera/one+clear+voice_20107351.html,"The whole world is talkin', drownin' out my vo...",whole world talkin drownin voice hear noise co...,https://youtube.com/watch?v=uz2JrfbDpao,931935.0,3826.0
4,Devo,Jerkin' Back 'n' Forth,/d/devo/jerkin+back+n+forth_20039742.html,I know I let you tell me what to do \nYou wer...,know let tell confident know best thing arent ...,https://youtube.com/watch?v=xFvAmY3kkO0,656796.0,6783.0

In [ ]:
def light_clean(text):
    text = text.lower()
    text = re.sub(r'\[.*?\]', '', text)  
    text = re.sub(r'[^a-zA-Z\s]', '', text)  
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df["better_text"] = df["text"].apply(light_clean)

In [ ]:
print(df.shape)
print(df["cleaned_text"].isnull().sum())

(7388, 9)
0

In [21]:
model = SentenceTransformer('all-MiniLM-L6-v2')

In [24]:
X = model.encode(df["better_text"].tolist(), batch_size=32, show_progress_bar=True)

Batches: 100%|██████████| 231/231 [00:09<00:00, 23.56it/s]

In [ ]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=8, random_state=42)
df["cluster"] = kmeans.fit_predict(X)

df.head()

,artist,song,link,text,cleaned_text,youtube_link,views,likes,better_text,cluster
0,Bonnie Raitt,I Believe I'm In Love With You.,/b/bonnie+raitt/i+believe+im+in+love+with+you_...,I don't know what's wrong with me \nI've been...,dont know whats wrong ive foolish fool baby ca...,https://youtube.com/watch?v=Si0teRtHY8o,804405.0,12338.0,i dont know whats wrong with me ive been fooli...,7
1,Patsy Cline,Have You Ever Been Lonely,/p/patsy+cline/have+you+ever+been+lonely_10200...,Have you ever been lonely have you ever been b...,ever lonely ever blue ever loved someone love ...,https://youtube.com/watch?v=PYq9CZwjis4,527978.0,5407.0,have you ever been lonely have you ever been b...,7
2,Ofra Haza,Kol Haklafim,/o/ofra+haza/kol+haklafim_10196740.html,Hakol beyneynu nigmar \nHatza'er li lo 'azar ...,hakol beyneynu nigmar hatzaer li lo azar hazma...,https://youtube.com/watch?v=UAjS5WMzmr8,517.0,11.0,hakol beyneynu nigmar hatzaer li lo azar hazma...,6
3,Peter Cetera,One Clear Voice,/p/peter+cetera/one+clear+voice_20107351.html,"The whole world is talkin', drownin' out my vo...",whole world talkin drownin voice hear noise co...,https://youtube.com/watch?v=uz2JrfbDpao,931935.0,3826.0,the whole world is talkin drownin out my voice...,5
4,Devo,Jerkin' Back 'n' Forth,/d/devo/jerkin+back+n+forth_20039742.html,I know I let you tell me what to do \nYou wer...,know let tell confident know best thing arent ...,https://youtube.com/watch?v=xFvAmY3kkO0,656796.0,6783.0,i know i let you tell me what to do you were c...,5

In [27]:
for i in range(8):
    print(f"\n--- Cluster {i} ---")
    print(df[df["cluster"] == i]["better_text"].sample(3).values)

--- Cluster 0 ---
['on her television on her mommas radio she could paint a picture more alive than all she ought to know her imagination running wild she let it grow in her imagination oh she found she loved him so the eyes of the girl are following me looking for the man that she pinned on me the tears for a love that could never be now its all over theyre raining on me oh its raining its an empty world with a lifetime on your hands oh we must believe that something someone somewhere understands our imagination wants to capture what we feel in our imagination everything is real tears fall from the eyes of the girl and the girl is watching me tears fall from the eyes of the girl and the girl is watching me baby please release me from the power of your mind baby please release me leave this crazy scheme behind baby please release me baby please release me the eyes of the girl are following me now its all over theyre raining on me oh its raining tears fall from the eyes of the girl and the girl is watching me tears fall from the eyes of the girl and the girl is watching me the eyes of the girl are following me eyes of the girl looking for the man that she pinned on me eyes of the girl the eyes of the girl eyes of the girl looking for the man eyes of the girl'
 'im scared of opening the can scared of changing who i am mightve taken all i can im scared of everything i am are you a natural woman i know ive got it comin the scent in the air and the water running the damage she said shes not telling it today she said come back when youre alone come back when youre alone the damage the damage the damage the damage the damn damn dam damage are you a natural woman i know ive got it comin dissent in the air and the water running dont give me whats in the window babe i want the stuff you think would never sell whatcha have under the counter on the bottom shelf ill buy the lowdown deepdown primal truthful self i let the genie out of the box i let the genie out of the box are you a natural woman i know ive got it comin the scent in the air and the water running are you a natural woman tell me youre the milliontoone are you a natural woman are you a natural woman im a natural man'
 'i see in the green stream that meanders round my mind a girl standing with arms so warm and kind she reaches out she calls my name but i just cant get through i know shes waiting in a land of sunny rain and i know that ill find my girl and its there i will remain ill lay right down and there ill stay cause there is paradise ive often felt her breathing as i rolled around your streets and so i look around me but we never chance to meet the golden girl with eyes of green a girl just meant for me i see in the green stream that meanders round my mind a girl standing with arms so warm and kind shes standing there she calls my name but i just cant get through']

--- Cluster 1 ---
['from this day on ill watch the setting sun as if it might be my last and as i view the changing color hue i see the long shadows pass van go gan van go gan get a a grip if you can van go gan van go gan watch it slip through your hands and through these eyes all the starry skies in my mind will explode as i lie in my bed at night i see my lifeline erode van go gan van go gan grab ahold if you can van go gan van go gan something i understand so much waiting sentimental memories hesitating maybe im just a wanna be van go gan van go gan get a grip if you can van go gan van go gan watch it slip through your hands van go gan van go gan something i understand'
 'i believed in fairy tales in magic spells and wishing wells and pirate sails and once i thought id never fall in love that shows how much i knew i believed in superman in santa claus the world of oz and wonderland but one by one those fantasies have failed while you keep shining through i still believe in you i could never doubt your kiss no other love fills me like this if you take a chance youll see i believe in you believe in me other dreams may turn to dust but i dont care if youll be there ill always trust cause i believe with all my heart and soul this dream we share is true i still believe in you'
 'does summer exist in its praises does summer exist in its praises the summer lives here where this place is come on up here weve got something to show you wanna show you everything we know wanna show you weve been banished before you wanna show you weve got our own roads and does your family know your wishes cause this chorus will do you like the dishes summers killin us its just sing sing sing all day its as if summer existed in its praises come on over ive got somethin to play you back at sunshine its the shadow band we can have strictly cactus relations telling the waves to stop crashing and does anybody know your wishes cause this tunell do you like the dishes this summers killin us its just sing sing sing all day its as if summer just exists in her praises a time for more to happen sooner a time to be a person you still know to float a while on your sure power till you say canada lost go home the summers killin us we sing sing sing all day and its as if summer exists here in its praises ooh summer exists in a doorway summer exists at the fair summer is forever changes summers taking me all the way']

--- Cluster 2 ---
['is it my fortune or my fame is it my money or my name is it my personality or just my sexuality yeah yeah what is my charisma what is my charisma yeah is it my body or my brain do i drive you insane ha is it the power of my touch do you need me too much too much too much what is my charisma what is my what is my what is my charisma is it my fortune or my fame what is my is it my money or my name charisma yeah what is my yeah yeah yeah charisma what is my charisma what is it ive got what is it about me that gets you so hot hot yeah am i the master of your soul do you lose all control ha is it my fire or my flame do i drive you insane charisma what is my charisma yeah what is my is it my fire or my flame charisma what is my charisma what is my charisma is it my body or my brain what is my is it my money or my name charisma and do i drive you insane what is my what is my what is my charisma what is my is it my fortune or my fame charisma and do i drive you insane what is my what is my what is my charisma what is my what is my what is my charisma charisma charisma what is my what is my what is my charisma what is my what is my what is my charisma charisma charisma what is my what is my what is my charisma'
 'at a truck stop in st angelo saw a bill board about this rodeo this weekend out in el paso so i signed up to ride i drew a bull called original sin heard hed killed a couple of men figured this was something i could win cause the devil was on my side i was havin myself one hell of a ride but i ended up disqualified that bull just up and died before they blew the whistle with those north texas blues thought id paid all my dues then those south texas blues told me son you aint through had the east texas blues and the west texas too ive done all i know to do tryin to lose tryin to lose these ol lone star blues well i got laid off at brown and rue then on my way back to cuttin chute i lost my wrist watch and my boots shootin dice with a dude from houston well there aint no jobs here workin cattle so i got on the part time haulin gravel with some outfit from seattle out here building custom homes well i gassed my truck and i packed my clothes turned in my key and i hit the road i said cow towns where ill go you never know i might get lucky well i got a friend there turning knobs at a place called billy bobs said thought he could get me a job there workin as a bouncer first night on the job was just insane some ol boy got all deranged hit me in the head with a harley chain to this day my ears still ring ive done all i know to do tryin to lose tryin to lose these ol lone star blues'
 'oh i know a place called good time charleys a little four piece band swingin out of sight and ill be here if you want to party come nine in the morning til twelve at night two miles from town cross the railroad track turn right at the light and park in the back youre always welcome dont forget to drop in old good time charleys any time you can well i heard talk bout a troublemaker dropped in one night and never came again well they said he left with an undertaker old charleys done time two years in the pen well the beat goes on theres a hardwood floor and the sound of laughter runnin out the door wall to wall women plenty of icecold beer anything youre after you can find in here two miles from town cross the railroad track turn right at the light and park in the back youre always welcome dont forget to drop in old good time charleys any time you can and youre always welcome dont forget to drop in old good time charleys any time you can']

--- Cluster 3 ---
['there is no time to sit around and wait dont you know the world it is of love and of hate now is the time weve got to be strong we cant go wrong because the time has come the time has come to be free cant you see dont you know the cheating the killing backbiting it cannot help cause cant you see them problems its everyday theyve got to solve themselves cause now is the time we gotta be strong we cant go wrong because the time has come the time has come to be free cant you see there is no time to sit around and wait dont you know the world it is of love and of hate cause now is the time weve got to be strong we cant go wrong because the time has come the time has come to be free cant you see'
 'we are nothing they own our lives just a statue of a stain in time spinning in circles got left behind we were all warned this would happen but the words just rang in our ears machines built by machines built by machines we can only hide for so long before they harvest us for the souls that we have left i swear we cannot wake up from this hell that we live in but when the sun finally hits our face we see that we are merely reflections of reflections left by our predecessors dragged through the mud we cant wake up chained by the ankle there is no more running there is no more escaping if only god could lay his hands down on this barren land and wake us up cause we are the lost we are the helpless we are the forgotten ones we are the lost and we are the abandoned i swear its worth saving us we pray for the sun to dry us up i need a clearer head to see what we are worth theres still life left down here to revolt oh i know what it looks like from there a loss of control to this place and were set to extinct revolt we stood by defeat for so long weve been under your control we will not be a part of your disease'
 'try to remember those ancient evenings when all we had was just enough now the pretender knows why the king is screaming the grief was finally just too much im going to ride with the idol like a creature on display tied to the bottom of a cage ride with the idol but it wont turn out the same i know they wont blow out the flame over my shoulder i know theyre waiting their dirty hands are everywhere and as they get closer all the pretense is fading the face beneath the skin is bare so now i ride with the idol like a creature on display tied to the bottom of a cage oh yeah ride with the idol but it wont turn out the same i know they wont blow out the flame i can never learn to say no wont they ever let me go im going to ride with the idol like a creature on display tied to the bottom of a cage oh yeah yeah ride with the idol but it wont turn out the same i know they wont blow out the flame ride with the idol like a creature on display tied to the bottom of a cage oh yeah yeah ride with the idol but it wont turn out the same i know they wont blow out the flame fade']

--- Cluster 4 ---
['on the road but i wont be gone for long babe im leavin you tomorrow on my way and you know you make me strong ill be thinkin about you all night long mama take just a little bit mama take just a little bit mama take just a little bit from my heart mama shake just a little bit mama brake just a little bit mama take just a little bit from my heart all alone and im feelin down today wont let nothin come between us say the words and the words are meant to say ill be thinkin about you everyday mama take just a little bit mama take just a little bit mama take just a little bit from my heart mama shake just a little bit mama brake just a little bit mama take just a little bit from my heart from my heart i believe that we belong beyond a doubt if we have a change of heart we can always change our mind and i know well work it out i can see that its the only way to go its the only chance i get its the only way youll know that i love to love you mighty love gettin hard to find today i believe in you forever say the words and the words are meant to say ill be thinkin about you everyday mama take just a little bit mama take just a little bit mama take just a little bit from my heart mama shake just a little bit mama brake just a little bit mama take just a little bit from my heart mama take just a little bit mama take just a little bit mama take just a little bit from my heart mama shake just a little bit mama brake just a little bit mama take just a little bit from my heart mama take just a little bit mama take just a little bit mama take just a little bit from my heart'
 'suspicions rising answers arent clear i thought we made a promise now youve disappeared you seem to lead two lives at a time do i still fit in i thought you were mine sitting at the bar in our favorite cafe i turn and see ya laughin with her and your smile fades away didnt surprise me theres nothin left to say i caught you redhanded now and you cant walk away chorus you were caught in the act when you thought i wasnt lookin at ya cita i can see what youre doin caught in the act and i cant stand to hear your lies caught in the act dont you try and change my mind you called me the only you said shes only a friend dont pretend youre sorry my heart will mend dont you come back to me dont you try to call you couldnt hold my heart with love now you cant hold me at all chorus caught in the act caught in the act caught in the act cita caught in the act caught in the act caught in the act cita'
 'oh baby you know i may be a fool im wastin my time by goin to school the way you got me holdin your door i cant do my homework anymore i cant do my homework anymore oh baby i said you got me so blind im walkin round in circles i could loose my mind the way you got me holdin your door i cant do my homework anymore now baby your as sweet as you can be everything you do keep on sending me just the kiss of your lips or the touch of your hand everything you do is really grand oh baby oh now what can i do im walkin round in circles in love with you the way you got me holdin your door i cant do my homework anymore now baby your as sweet as you can be everything you do keep on sending me just the kiss of your lips or the touch of your hand everything you do is really grand oh baby oh now what can i do im walkin round in circles in love with you the way you got me holdin your door i cant do my homework anymore i cant do my homework anymore i cant do my homework anymore i cant do my homework anymore i cant do my homework anymore']

--- Cluster 5 ---
['jerry says that in the dark i think i have a good idea that i should do the opposite of whatever it is i feel thats because i have a bad mind and i have gold in my veins but he said i got the purest heart that hes ever seen what god gave me a brain for if he wont let me use it what god give me a plan for if he wont help me do it youre gonna love me im gonna make you youre gonna love me im gonna make you i can tell that youre the type to never trust a beauty queen but i was never voted for nothing and highschool never meant anything to anybody never ever gave myself away but even when im funny you think im acting so i say what god give me a break for if he wont let me use it what god give me a plan for he never helps me do it youre gonna love me im gonna make you youre gonna love me im gonna make you you say that you dont want to be hypnotized but baby i i dont wanna hypnotize you theres nothing from you that i wanna take i just wanna be like you maybe love you just a little bit please tell em mom and daddy gave themselves i wont to you you told me to get my ways as i do what im gonna do im gonna strike out right now im striking out right now with this song but i cant help myself i cant do right for long what god give me a break for if he wont let me use it what god give me a wlan for he never helps me do it youre gonna love me im gonna make you youre gonna love me im gonna make you'
 'please mmmmmmyeah all you people cant you see cant you see how your loves affecting our reality everytime were down you can make it right and that makes you whoa right ooh ooh yeah oh cmon cmon yeah yeah cos all of our time spent in flashes of light all you people cant you see cant you see how your loves affecting our reality everytime were down you can make it right and that makes you larger than life whoa right yeah looking at the crowd and i see your body sway cmon wishin i could thank you in a different way cmon cmon all of your time spent keeps us alive all you people cant you see cant you see how your loves affecting our reality everytime were down you can make it right and that makes you larger than life whoa oh oh oh yeah cos all of your time spent keeps us alive thats right all you people cant you see cant you see how your loves affecting our reality everytime were down you can make it right and that makes you larger than life yeah everytime were down yeah you can make it right yeah and thats what makes you larger than life all you people cant you see cant you see how your loves affecting our reality everytime were down you can make it right and that makes you larger than life'
 'sometimes id like to go to bed with a hundred women or men and lose my mind in lust and drink and to hit some people into feeling good oh sometimes id like to dance in the street dont wanna go to work just wanna lay in bed all day why dont you then why dont you then life just seems oh so meaningless and who can blame us for wanting these things but you just try being free my friend and everyone will hate your guts i only want to free']

--- Cluster 6 ---
['shall we gather at the river where bright angels feet have trod with its crystal tides forever flowing by the throne of god yes well gather at that river the beautiful the beautiful river gather with the saints at that river that flows by the throne of god when we reach that shining river well lay every burden down then grace our spirits will deliver and will receive our robe and crown yes well gather at that river the beautiful the beautiful river gather with the saints at that river that flows by the throne of god soon well reach that silver river soon our pilgrimage will cease soon our happy hearts will quiver with the melody of peace yes well gather at that river the beautiful the beautiful river gather with the saints at that river that flows by the throne of god oh yes well gather at that river that flows by the throne of god that flows by the throne of god'
 'sweet september i remember eyes of august deepest blue while the lazy town was sleeping strangest love that i ever knew feel the wind blow see the shadows kiss the breeze of a sudden shore of my lifes loves and fascinations the only one who left me wanting more little blonde plaits drink to you love drink to me love sun burned feet on a dusty track evening waves that turned in twilight caught forever those little blonde plaits'

In [29]:
df["cluster"].value_counts()

cluster
2    1210
1    1070
4    1068
7    1039
5     919
3     834
0     637
6     611
Name: count, dtype: int64

In [30]:
cluster_map = {
    0: "love_sad",
    1: "love",
    2: "happy",
    3: "motivational",
    4: "love_sad",
    5: "happy",
    6: "religious",
    7: "love"
}

In [31]:
df["label"] = df["cluster"].map(cluster_map)

df["label"].value_counts()
df["label"].value_counts(normalize=True) * 100

label
happy           28.817001
love            28.546291
love_sad        23.077964
motivational    11.288576
religious        8.270168
Name: proportion, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

import joblib

In [33]:
y = df["label"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y 
)

In [35]:
models = {
    "LogisticRegression": LogisticRegression(max_iter=2000, class_weight='balanced'),
    "RandomForest": RandomForestClassifier(n_estimators=200),
    "SVM": SVC(probability=True, class_weight='balanced')
}

In [36]:
results = {}

for name, model in models.items():
    print(f"\nTraining {name}...")
    
    model.fit(X_train, y_train)
    
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    
    results[name] = acc
    
    print(f"{name} Accuracy: {acc:.4f}")

Training LogisticRegression...
LogisticRegression Accuracy: 0.8173

Training RandomForest...
RandomForest Accuracy: 0.7666

Training SVM...
SVM Accuracy: 0.8748

In [37]:
best_model_name = max(results, key=results.get)
best_accuracy = results[best_model_name]

print("Best Model:", best_model_name)
print("Best Accuracy:", best_accuracy)

Best Model: SVM
Best Accuracy: 0.874830852503383

In [38]:
best_model = models[best_model_name]

joblib.dump(best_model, "best_model.pkl")

['best_model.pkl']

In [39]:
joblib.dump(model, "embedding_model.pkl")

['embedding_model.pkl']

In [40]:
df.to_csv("songs_clustered.csv", index=False)